// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKs_W52AoCl96smmhCobXzBDlxv-xkTUA',
    appId: '1:712205649791:web:65957058ca2306c4913c4a',
    messagingSenderId: '712205649791',
    projectId: 'vision-ia-bbd26',
    authDomain: 'vision-ia-bbd26.firebaseapp.com',
    storageBucket: 'vision-ia-bbd26.appspot.com',
    measurementId: 'G-5J9678FP23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDivOYC3mj6VxkhO03JqFeXTOxPTBaXDQw',
    appId: '1:712205649791:android:ea97b8bc6457c31d913c4a',
    messagingSenderId: '712205649791',
    projectId: 'vision-ia-bbd26',
    storageBucket: 'vision-ia-bbd26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT4Ak3ZCl-EIUydrtTO5xj2Rb2GpvuDLA',
    appId: '1:712205649791:ios:461e04f6b5d2ce6c913c4a',
    messagingSenderId: '712205649791',
    projectId: 'vision-ia-bbd26',
    storageBucket: 'vision-ia-bbd26.appspot.com',
    iosClientId: '712205649791-rgt4h96o9cet0isr5p8et4b0cg17qgg2.apps.googleusercontent.com',
    iosBundleId: 'com.google.ml.kit.flutter.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT4Ak3ZCl-EIUydrtTO5xj2Rb2GpvuDLA',
    appId: '1:712205649791:ios:86fbf6ce02444a4a913c4a',
    messagingSenderId: '712205649791',
    projectId: 'vision-ia-bbd26',
    storageBucket: 'vision-ia-bbd26.appspot.com',
    iosClientId: '712205649791-vh3skd3bb2vfinns3u77qrr0ba8kiqf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.visualIa.RunnerTests',
  );
}
